"""Pydantic domain entity for lead activities (timeline rows).

Activities are append-only — no edit, no delete through the API. The
service is the only writer. Five types:

- ``call`` / ``email`` / ``meeting`` / ``note`` — user-logged
  touchpoints. The first three are contact attempts; ``note`` is a
  catch-all for "she said she'd think about it."
- ``status_change`` — system-generated on every pipeline transition.
  Carries the old + new status (and the lost reason, when applicable)
  in the ``note`` field as plain text. Clients cannot send this type
  via ``POST /leads/{id}/activities`` — the service rejects it with
  422.

The entity carries no methods. All business logic lives in
``LeadService``; the data shape here is uniform.
"""

from datetime import datetime
from enum import StrEnum
from uuid import UUID

from pydantic import BaseModel, Field


class LeadActivityType(StrEnum):
    """Activity type. ``status_change`` is system-only."""

    CALL = "call"
    EMAIL = "email"
    NOTE = "note"
    MEETING = "meeting"
    STATUS_CHANGE = "status_change"


class LeadActivity(BaseModel):
    """One row in the lead's append-only timeline."""

    id: UUID
    tenant_id: UUID = Field(
        description=(
            "Denormalized for fast tenant scoping. Always equals the "
            "parent lead's tenant_id; the FK to tenants is for cascade."
        ),
    )
    lead_id: UUID
    type: LeadActivityType
    note: str = Field(description="Free-text body. NOT optional — empty notes are useless.")
    created_by: UUID | None = Field(
        default=None,
        description=(
            "User who logged this row. NULL when the row was generated by "
            "a system task (none planned today, but reserved)."
        ),
    )
    created_at: datetime
