/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Platform-wide aggregate counts
         * @description super_admin only. Returns total/active tenant counts, new-tenants-this-month, total users, and total members across all tenants. Powers the admin dashboard.
         */
        get: operations["get_platform_stats_api_v1_admin_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login with email and password
         * @description Returns a JWT access token in an HttpOnly cookie (for the frontend) and in the response body (for Swagger / API clients). Rate limited: 10 requests per minute per IP.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Clears the HttpOnly cookie and blacklists the token in Redis so it can't be reused even if intercepted.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user profile
         * @description Returns the user profile for the authenticated token.
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List class types
         * @description Lists classes in the caller's tenant. Any tenant user can read. Pass ``include_inactive=true`` (owner) to see deactivated classes.
         */
        get: operations["list_classes_api_v1_classes_get"];
        put?: never;
        /**
         * Create a class type
         * @description Owner-only. Creates a new class type in the caller's tenant. Name must be unique within the tenant.
         */
        post: operations["create_class_api_v1_classes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes/{class_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a class by ID */
        get: operations["get_class_api_v1_classes__class_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a class (partial)
         * @description Owner-only. Rename, re-color, edit description.
         */
        patch: operations["update_class_api_v1_classes__class_id__patch"];
        trace?: never;
    };
    "/api/v1/classes/{class_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-activate a deactivated class
         * @description Owner-only. Sets is_active=true.
         */
        post: operations["activate_class_api_v1_classes__class_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes/{class_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deactivate a class (soft)
         * @description Owner-only. Sets is_active=false — existing plan_entitlements and class_passes keep working, but new subscriptions can't reference this class.
         */
        post: operations["deactivate_class_api_v1_classes__class_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List members
         * @description List members in the caller's tenant. Filterable by status and search.
         */
        get: operations["list_members_api_v1_members_get"];
        put?: never;
        /**
         * Create a new member
         * @description Creates a member in the caller's tenant. Phone must be unique within the tenant.
         */
        post: operations["create_member_api_v1_members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a member by ID */
        get: operations["get_member_api_v1_members__member_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a member (partial) */
        patch: operations["update_member_api_v1_members__member_id__patch"];
        trace?: never;
    };
    "/api/v1/members/{member_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a member (terminal)
         * @description owner+ only. Sets status=cancelled. Data is preserved.
         */
        post: operations["cancel_member_api_v1_members__member_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{member_id}/freeze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Freeze a member
         * @description Pauses the subscription without cancelling. Only active members can be frozen.
         */
        post: operations["freeze_member_api_v1_members__member_id__freeze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{member_id}/unfreeze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unfreeze a member
         * @description Returns a frozen member to active status.
         */
        post: operations["unfreeze_member_api_v1_members__member_id__unfreeze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all tenants
         * @description super_admin only. Returns all gyms on the platform.
         */
        get: operations["list_tenants_api_v1_tenants_get"];
        put?: never;
        /**
         * Onboard a new gym
         * @description Only super_admin can create tenants.
         */
        post: operations["create_tenant_api_v1_tenants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a tenant by ID */
        get: operations["get_tenant_api_v1_tenants__tenant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a tenant (partial)
         * @description super_admin only. Only provided fields are updated.
         */
        patch: operations["update_tenant_api_v1_tenants__tenant_id__patch"];
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate a tenant
         * @description super_admin only. Moves a tenant to active (from trial, suspended, or cancelled).
         */
        post: operations["activate_tenant_api_v1_tenants__tenant_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a tenant (soft delete)
         * @description super_admin only. Sets status to cancelled. Data is preserved; this is reversible by calling /activate.
         */
        post: operations["cancel_tenant_api_v1_tenants__tenant_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Per-tenant stats
         * @description Counts for the tenant detail page — members (total + active) and users. super_admin can view any tenant; tenant users can only view their own.
         */
        get: operations["get_tenant_stats_api_v1_tenants__tenant_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suspend a tenant
         * @description super_admin only. Blocks all users of this gym from accessing the platform.
         */
        post: operations["suspend_tenant_api_v1_tenants__tenant_id__suspend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users of a tenant
         * @description super_admin only. Use GET /users instead for self-tenant listing.
         */
        get: operations["list_tenant_users_api_v1_tenants__tenant_id__users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/logo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a tenant logo
         * @description Accepts PNG, JPEG, WebP, or SVG up to 2 MB. Returns the S3 key and a short-lived presigned URL. super_admin only — this is used during tenant onboarding.
         */
        post: operations["upload_logo_api_v1_uploads_logo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description super_admin sees all users. owner/staff/sales see only their tenant.
         */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        /**
         * Create a new user
         * @description Only super_admin can create users. Tenant-scoped roles (admin/manager/worker) require a tenant_id.
         */
        post: operations["create_user_api_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user by ID */
        get: operations["get_user_api_v1_users__user_id__get"];
        put?: never;
        post?: never;
        /**
         * Soft-delete a user
         * @description Sets is_active=false. No data is removed. Owner or above.
         */
        delete: operations["delete_user_api_v1_users__user_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update a user (partial)
         * @description Owner or above. Only provided fields are updated.
         */
        patch: operations["update_user_api_v1_users__user_id__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_logo_api_v1_uploads_logo_post */
        Body_upload_logo_api_v1_uploads_logo_post: {
            /** File */
            file: string;
        };
        /**
         * CreateGymClassRequest
         * @description POST /api/v1/classes — create a class in the caller's tenant.
         * @example {
         *       "color": "#3B82F6",
         *       "description": "High-intensity indoor cycling",
         *       "name": "Spinning"
         *     }
         */
        CreateGymClassRequest: {
            /**
             * Color
             * @description Hex code recommended (e.g. '#3B82F6'). Not validated.
             */
            color?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Name
             * @description Unique within tenant
             */
            name: string;
        };
        /**
         * CreateMemberRequest
         * @description POST /api/v1/members — create a new member in the caller's tenant.
         *
         *     ``first_name``, ``last_name``, and ``phone`` are required.
         *     ``join_date`` defaults to today (server-side) when omitted.
         * @example {
         *       "custom_fields": {
         *         "referral_source": "walk_in"
         *       },
         *       "email": "dana@example.com",
         *       "first_name": "Dana",
         *       "gender": "female",
         *       "last_name": "Cohen",
         *       "phone": "+972-50-123-4567"
         *     }
         */
        CreateMemberRequest: {
            /**
             * Custom Fields
             * @description Ad-hoc per-tenant data. Do not put structured queryable data here.
             */
            custom_fields?: {
                [key: string]: unknown;
            };
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** Email */
            email?: string | null;
            /** First Name */
            first_name: string;
            /** Gender */
            gender?: string | null;
            /**
             * Join Date
             * @description Defaults to today if omitted
             */
            join_date?: string | null;
            /** Last Name */
            last_name: string;
            /** Notes */
            notes?: string | null;
            /**
             * Phone
             * @description Unique within tenant
             */
            phone: string;
        };
        /**
         * CreateTenantRequest
         * @description POST /api/v1/tenants — onboard a new gym.
         *
         *     Only ``slug`` and ``name`` are required. Everything else is optional
         *     and can be filled in later via PATCH.
         * @example {
         *       "address_city": "אור יהודה",
         *       "address_country": "IL",
         *       "address_postal_code": "6578901",
         *       "address_street": "יוני נתניהו 5",
         *       "currency": "ILS",
         *       "email": "mark@dopamineogym.com",
         *       "legal_name": "דופמינו בע״מ",
         *       "locale": "he-IL",
         *       "name": "דופמינו ג׳ים",
         *       "phone": "0543123090",
         *       "slug": "dopamineogym-or-yheuda",
         *       "tax_id": "123456789",
         *       "timezone": "Asia/Jerusalem",
         *       "website": "https://dopamineo.co.il/"
         *     }
         */
        CreateTenantRequest: {
            /** Address City */
            address_city?: string | null;
            /**
             * Address Country
             * @description ISO 3166-1 alpha-2
             * @default IL
             */
            address_country: string | null;
            /** Address Postal Code */
            address_postal_code?: string | null;
            /** Address Street */
            address_street?: string | null;
            /**
             * Currency
             * @description ISO 4217 currency code
             * @default ILS
             */
            currency: string;
            /**
             * Email
             * @description Business email for notifications
             */
            email?: string | null;
            /**
             * Legal Name
             * @description Legal business name
             */
            legal_name?: string | null;
            /**
             * Locale
             * @description BCP 47 locale
             * @default he-IL
             */
            locale: string;
            /**
             * Logo Url
             * @description S3 key from /uploads/logo
             */
            logo_url?: string | null;
            /**
             * Name
             * @description Display name of the gym
             */
            name: string;
            /** Phone */
            phone?: string | null;
            /**
             * Slug
             * @description URL-safe identifier (unique). Lowercase English letters, digits, and hyphens only — no spaces, uppercase, or non-Latin characters.
             */
            slug: string;
            /**
             * Tax Id
             * @description ח.פ / ע.מ
             */
            tax_id?: string | null;
            /**
             * Timezone
             * @description IANA timezone
             * @default Asia/Jerusalem
             */
            timezone: string;
            /** Website */
            website?: string | null;
        };
        /**
         * CreateUserRequest
         * @description POST /api/v1/users — create a new user.
         * @example {
         *       "email": "owner@dopagym.com",
         *       "first_name": "Dana",
         *       "last_name": "Cohen",
         *       "password": "SecureP@ss123",
         *       "role": "owner",
         *       "tenant_id": "550e8400-e29b-41d4-a716-446655440000"
         *     }
         */
        CreateUserRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Oauth Id */
            oauth_id?: string | null;
            /** Oauth Provider */
            oauth_provider?: string | null;
            /**
             * Password
             * @description Min 8 chars, at least 1 uppercase and 1 special character
             */
            password?: string | null;
            /** Phone */
            phone?: string | null;
            role: components["schemas"]["Role"];
            /**
             * Tenant Id
             * @description Required for owner/staff/sales. Null for super_admin.
             */
            tenant_id?: string | null;
        };
        /**
         * FreezeMemberRequest
         * @description POST /api/v1/members/{id}/freeze — optional body.
         */
        FreezeMemberRequest: {
            /**
             * Until
             * @description Optional auto-unfreeze date. Null means indefinite freeze.
             */
            until?: string | null;
        };
        /**
         * GymClassResponse
         * @description Standard gym class response shape.
         * @example {
         *       "color": "#3B82F6",
         *       "created_at": "2026-04-16T10:00:00+03:00",
         *       "description": "High-intensity indoor cycling",
         *       "id": "11111111-1111-1111-1111-111111111111",
         *       "is_active": true,
         *       "name": "Spinning",
         *       "tenant_id": "550e8400-e29b-41d4-a716-446655440000",
         *       "updated_at": "2026-04-16T10:00:00+03:00"
         *     }
         */
        GymClassResponse: {
            /** Color */
            color: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginRequest
         * @description POST /api/v1/auth/login
         * @example {
         *       "email": "admin@dopacrm.com",
         *       "password": "your-password"
         *     }
         */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MemberResponse
         * @description Standard member response shape.
         * @example {
         *       "created_at": "2026-04-14T12:00:00+03:00",
         *       "custom_fields": {
         *         "referral_source": "walk_in"
         *       },
         *       "date_of_birth": "1990-05-15",
         *       "email": "dana@example.com",
         *       "first_name": "Dana",
         *       "gender": "female",
         *       "id": "11111111-1111-1111-1111-111111111111",
         *       "join_date": "2026-04-14",
         *       "last_name": "Cohen",
         *       "phone": "+972-50-123-4567",
         *       "status": "active",
         *       "tenant_id": "550e8400-e29b-41d4-a716-446655440000",
         *       "updated_at": "2026-04-14T12:00:00+03:00"
         *     }
         */
        MemberResponse: {
            /** Cancelled At */
            cancelled_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Custom Fields */
            custom_fields: {
                [key: string]: unknown;
            };
            /** Date Of Birth */
            date_of_birth: string | null;
            /** Email */
            email: string | null;
            /** First Name */
            first_name: string;
            /** Frozen At */
            frozen_at: string | null;
            /** Frozen Until */
            frozen_until: string | null;
            /** Gender */
            gender: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Join Date
             * Format: date
             */
            join_date: string;
            /** Last Name */
            last_name: string;
            /** Notes */
            notes: string | null;
            /** Phone */
            phone: string;
            status: components["schemas"]["MemberStatus"];
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * MemberStatus
         * @description Lifecycle status of a member.
         * @enum {string}
         */
        MemberStatus: "active" | "frozen" | "cancelled" | "expired";
        /**
         * PlatformStatsResponse
         * @description Aggregate counts across every tenant on the platform.
         *
         *     Powers the super_admin dashboard (AdminDashboard.tsx on the frontend).
         * @example {
         *       "active_tenants": 10,
         *       "new_tenants_this_month": 3,
         *       "total_members": 387,
         *       "total_tenants": 12,
         *       "total_users": 45
         *     }
         */
        PlatformStatsResponse: {
            /** Active Tenants */
            active_tenants: number;
            /** New Tenants This Month */
            new_tenants_this_month: number;
            /** Total Members */
            total_members: number;
            /** Total Tenants */
            total_tenants: number;
            /** Total Users */
            total_users: number;
        };
        /**
         * Role
         * @description User role hierarchy.
         *
         *     ``super_admin`` is platform-level (``tenant_id = None``).
         *     Every other role belongs to exactly one company (gym tenant).
         *
         *     - owner: full tenant access, billing, configuration
         *     - staff: day-to-day operations (check-in, payments, members)
         *     - sales: lead pipeline, trials, conversions
         * @enum {string}
         */
        Role: "super_admin" | "owner" | "staff" | "sales";
        /**
         * TenantResponse
         * @description Standard tenant response.
         * @example {
         *       "address_city": "אור יהודה",
         *       "address_country": "IL",
         *       "address_postal_code": "6578901",
         *       "address_street": "יוני נתניהו 5",
         *       "created_at": "2026-04-15T12:00:00+03:00",
         *       "currency": "ILS",
         *       "email": "mark@dopamineogym.com",
         *       "id": "550e8400-e29b-41d4-a716-446655440000",
         *       "legal_name": "דופמינו בע״מ",
         *       "locale": "he-IL",
         *       "name": "דופמינו ג׳ים",
         *       "phone": "0543123090",
         *       "saas_plan_id": "aaaa0000-0000-0000-0000-000000000000",
         *       "slug": "dopamineogym-or-yheuda",
         *       "status": "trial",
         *       "tax_id": "123456789",
         *       "timezone": "Asia/Jerusalem",
         *       "trial_ends_at": "2026-04-29T12:00:00+03:00",
         *       "updated_at": "2026-04-15T12:00:00+03:00",
         *       "website": "https://dopamineo.co.il/"
         *     }
         */
        TenantResponse: {
            /** Address City */
            address_city: string | null;
            /** Address Country */
            address_country: string | null;
            /** Address Postal Code */
            address_postal_code: string | null;
            /** Address Street */
            address_street: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Currency */
            currency: string;
            /** Email */
            email: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Legal Name */
            legal_name: string | null;
            /** Locale */
            locale: string;
            /**
             * Logo Presigned Url
             * @description Short-lived presigned URL to the logo (1 hour). Null if no logo.
             */
            logo_presigned_url?: string | null;
            /** Logo Url */
            logo_url: string | null;
            /** Name */
            name: string;
            /** Phone */
            phone: string | null;
            /**
             * Saas Plan Id
             * Format: uuid
             */
            saas_plan_id: string;
            /** Slug */
            slug: string;
            status: components["schemas"]["TenantStatus"];
            /** Tax Id */
            tax_id: string | null;
            /** Timezone */
            timezone: string;
            /** Trial Ends At */
            trial_ends_at: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Website */
            website: string | null;
        };
        /**
         * TenantStatsResponse
         * @description Per-tenant counters shown on the tenant detail page.
         * @example {
         *       "active_members": 38,
         *       "total_members": 42,
         *       "total_users": 5
         *     }
         */
        TenantStatsResponse: {
            /** Active Members */
            active_members: number;
            /** Total Members */
            total_members: number;
            /** Total Users */
            total_users: number;
        };
        /**
         * TenantStatus
         * @description Lifecycle status of a tenant.
         * @enum {string}
         */
        TenantStatus: "trial" | "active" | "suspended" | "cancelled";
        /**
         * TokenResponse
         * @description Returned on successful login or token refresh.
         * @example {
         *       "access_token": "<jwt-token>",
         *       "expires_in": 28800,
         *       "token_type": "bearer"
         *     }
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * UpdateGymClassRequest
         * @description PATCH /api/v1/classes/{id} — partial update.
         * @example {
         *       "color": "#10B981",
         *       "description": "Updated description"
         *     }
         */
        UpdateGymClassRequest: {
            /** Color */
            color?: string | null;
            /** Description */
            description?: string | null;
            /** Name */
            name?: string | null;
        };
        /**
         * UpdateMemberRequest
         * @description PATCH /api/v1/members/{id} — partial update. All fields optional.
         * @example {
         *       "notes": "Moved to morning sessions",
         *       "phone": "+972-52-999-0000"
         *     }
         */
        UpdateMemberRequest: {
            /** Custom Fields */
            custom_fields?: {
                [key: string]: unknown;
            } | null;
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** Email */
            email?: string | null;
            /** First Name */
            first_name?: string | null;
            /** Gender */
            gender?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Notes */
            notes?: string | null;
            /** Phone */
            phone?: string | null;
        };
        /**
         * UpdateTenantRequest
         * @description PATCH /api/v1/tenants/{tenant_id} — partial update.
         * @example {
         *       "name": "דופמינו ג׳ים — אור יהודה",
         *       "phone": "0543123090"
         *     }
         */
        UpdateTenantRequest: {
            /** Address City */
            address_city?: string | null;
            /** Address Country */
            address_country?: string | null;
            /** Address Postal Code */
            address_postal_code?: string | null;
            /** Address Street */
            address_street?: string | null;
            /** Currency */
            currency?: string | null;
            /** Email */
            email?: string | null;
            /** Legal Name */
            legal_name?: string | null;
            /** Locale */
            locale?: string | null;
            /** Logo Url */
            logo_url?: string | null;
            /** Name */
            name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Tax Id */
            tax_id?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Website */
            website?: string | null;
        };
        /**
         * UpdateUserRequest
         * @description PATCH /api/v1/users/{user_id} — partial update.
         *
         *     super_admin can reset a user's password by including ``password`` here.
         *     Plaintext is hashed with argon2 in the service layer; it never touches
         *     the DB directly. Leave blank / omit to keep the existing password.
         * @example {
         *       "first_name": "Dana",
         *       "is_active": true,
         *       "last_name": "Cohen",
         *       "role": "staff"
         *     }
         */
        UpdateUserRequest: {
            /** Email */
            email?: string | null;
            /** First Name */
            first_name?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Last Name */
            last_name?: string | null;
            /**
             * Password
             * @description New password. Min 8 chars, 1 uppercase, 1 special character.
             */
            password?: string | null;
            /** Phone */
            phone?: string | null;
            role?: components["schemas"]["Role"] | null;
        };
        /**
         * UploadResponse
         * @description Response after a successful upload.
         *
         *     ``key`` is the S3 object key (with env prefix, e.g. ``dev/tenants/.../logo.png``).
         *     Store this on the entity (e.g. ``tenants.logo_url``).
         *
         *     ``presigned_url`` is a short-lived HTTPS URL the frontend can use to preview
         *     the file immediately without making a second request.
         * @example {
         *       "key": "dev/tenants/abc123/logo.png",
         *       "presigned_url": "https://dopacrm-uploads-....s3.amazonaws.com/..."
         *     }
         */
        UploadResponse: {
            /**
             * Key
             * @description Full S3 key including env prefix
             */
            key: string;
            /**
             * Presigned Url
             * @description Short-lived URL for preview (1 hour)
             */
            presigned_url: string;
        };
        /**
         * UserResponse
         * @description Standard user response — never includes password_hash.
         * @example {
         *       "created_at": "2026-04-09T12:00:00+03:00",
         *       "email": "owner@dopagym.com",
         *       "first_name": "Dana",
         *       "id": "bb22240d-f00d-47fc-ac60-aa5b08f550aa",
         *       "is_active": true,
         *       "last_name": "Cohen",
         *       "phone": "+972-50-123-4567",
         *       "role": "owner",
         *       "tenant_id": "550e8400-e29b-41d4-a716-446655440000",
         *       "updated_at": "2026-04-09T12:00:00+03:00"
         *     }
         */
        UserResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** First Name */
            first_name?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Last Name */
            last_name?: string | null;
            /** Oauth Provider */
            oauth_provider: string | null;
            /** Phone */
            phone?: string | null;
            role: components["schemas"]["Role"];
            /** Tenant Id */
            tenant_id: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_platform_stats_api_v1_admin_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformStatsResponse"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_classes_api_v1_classes_get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GymClassResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_class_api_v1_classes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGymClassRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GymClassResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_class_api_v1_classes__class_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                class_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GymClassResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_class_api_v1_classes__class_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                class_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGymClassRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GymClassResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_class_api_v1_classes__class_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                class_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GymClassResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_class_api_v1_classes__class_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                class_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GymClassResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_v1_members_get: {
        parameters: {
            query?: {
                /** @description Repeat to filter multiple */
                status?: components["schemas"]["MemberStatus"][] | null;
                /** @description Case-insensitive match against name, phone, email */
                search?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_member_api_v1_members_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMemberRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_member_api_v1_members__member_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_member_api_v1_members__member_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_member_api_v1_members__member_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    freeze_member_api_v1_members__member_id__freeze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FreezeMemberRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unfreeze_member_api_v1_members__member_id__unfreeze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tenants_api_v1_tenants_get: {
        parameters: {
            query?: {
                /** @description Max results */
                limit?: number;
                /** @description Skip N results */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tenant_api_v1_tenants_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTenantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tenant_api_v1_tenants__tenant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tenant_api_v1_tenants__tenant_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTenantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_tenant_api_v1_tenants__tenant_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_tenant_api_v1_tenants__tenant_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tenant_stats_api_v1_tenants__tenant_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suspend_tenant_api_v1_tenants__tenant_id__suspend_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tenant_users_api_v1_tenants__tenant_id__users_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_logo_api_v1_uploads_logo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_logo_api_v1_uploads_logo_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: {
                /** @description Max results */
                limit?: number;
                /** @description Skip N results */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_v1_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_v1_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
